version: "3"

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local

services:
  admin-panel-api:
    container_name: admin-panel-api-profolio-dev
    build:
      context: ./admin-panel-api
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - ./admin-panel-api/controller:/app/controller
      - ./admin-panel-api/config:/app/config
      - ./admin-panel-api/App.tsx:/app/App.tsx
    environment:
      - CHOKIDAR_USEPOLLING=true
      - KEY_CLOAK_CLIENT_ID=main-keycloak-client
      - KEY_CLOAK_REALM_NAME=MainAdminRealm
      - KEY_CLOAK_REALM_PUBLIC_KEY=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrVrCuTtArbgaZzL1hvh0xtL5mc7o0NqPVnYXkLvgcwiC3BjLGw1tGEGoJaXDuSaRllobm53JBhjx33UNv+5z/UMG4kytBWxheNVKnL6GgqlNabMaFfPLPCF8kAgKnsi79NMo+n6KnSY8YeUmec/p2vjO2NjsSAVcWEQMVhJ31LwIDAQAB
      - KEY_CLOAK_AUTH_SERVER_URL=http://localhost:8080/auth
      - KEY_CLOAK_SSL_REQUIRED=external
      - KEY_CLOAK_PUBLIC_CLIENT=true
      - KEY_CLOAK_CONFIDENTIAL_PORT=0
      - INVITE_EMAIL_ADRESS=profolio@dmowski.online
      - INVITE_EMAIL_PASSWORD=sjmqr8GQQWGLY8h
      - INVITE_EMAIL_HOST=mailbe05.hoster.by
      - INVITE_EMAIL_PORT=mailbe05.hoster.by
      - MONGODB_PORT=27017
    links:
      - mongodb
  mongodb:
    container_name: mongodb-profolio-dev
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  admin-panel:
    container_name: admin-panel-profolio-dev
    build:
      context: ./admin-panel
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./admin-panel/src:/app/src
      - ./admin-panel/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_KEY_CLOAK_CLIENT_ID=main-keycloak-client
      - REACT_APP_KEY_CLOAK_REALM_NAME=MainAdminRealm
      - REACT_APP_KEY_CLOAK_AUTH_SERVER_URL=http://localhost:8080/auth
      - REACT_APP_KEY_CLOAK_SSL_REQUIRED=external
      - REACT_APP_KEY_CLOAK_PUBLIC_CLIENT=true
      - REACT_APP_KEY_CLOAK_CONFIDENTIAL_PORT=0
      - REACT_APP_BACKEND_BASE_URL=http://localhost:9000
  welcome-page:
    container_name: welcome-page-profolio-dev
    build:
      context: ./welcome-page
      dockerfile: Dockerfile.dev
    ports:
      - "3010:3000"
    volumes:
      - ./welcome-page/src:/app/src
      - ./welcome-page/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_BASE_URL=http://localhost:9000
  postgres:
    container_name: postgres-profolio-dev
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    container_name: keycloak-profolio-dev
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - postgres
